# Generated by Django 3.0.6 on 2020-07-04 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=100)),
                ('saler', models.CharField(max_length=100)),
                ('sendTime', models.DateTimeField(blank=True, null=True)),
                ('acceptTime', models.DateTimeField(blank=True, null=True)),
                ('recvTime', models.DateTimeField(blank=True, null=True)),
                ('cancelTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(default='default/default.jpg', upload_to='photo')),
                ('contact', models.TextField(help_text='Enter a resume of student', max_length=500)),
                ('credit', models.FloatField(help_text='Enter recruit Number')),
                ('grade', models.IntegerField(help_text='Enter recruit Number')),
                ('resume', models.TextField(help_text='Enter a resume of student', max_length=1000)),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Genre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saler_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('saler', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('photo', models.ImageField(default='default/default.jpg', upload_to='photo')),
                ('timeRequire', models.IntegerField()),
                ('detail', models.TextField(help_text='Enter a resume of student', max_length=500)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(default='default/default.jpg', upload_to='photo')),
                ('contact', models.TextField(help_text='Enter a resume of student', max_length=500)),
                ('credit', models.FloatField(help_text='Enter recruit Number')),
                ('grade', models.IntegerField(help_text='Enter recruit Number')),
                ('resume', models.TextField(help_text='Enter a resume of student', max_length=1000)),
                ('prefer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Genre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
